# Generated by Django 3.2.12 on 2022-02-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('team_image', models.TextField(max_length=250)),
                ('team_text', models.ImageField(upload_to='IMG')),
            ],
        ),
        migrations.AlterField(
            model_name='whyitem',
            name='why_text',
            field=models.TextField(max_length=500),
        ),
    ]
